/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stego;

import java.awt.List;
import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.JFileChooser;

/**
 *
 * @author HPProbook4530s
 */
public class Main extends javax.swing.JFrame {

    public static void writeBytes(String fileName, byte[] data) throws Exception {
        FileOutputStream fop = new FileOutputStream(fileName);
        fop.write(data);
        fop.flush();
        fop.close();
    }


    /**
     * Creates new form SteqoFreym
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelGizlet = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonGizlet = new javax.swing.JButton();
        butonKonteyner = new javax.swing.JButton();
        textFieldKonteyner = new javax.swing.JTextField();
        textFieldMelumat = new javax.swing.JTextField();
        butonGizli = new javax.swing.JButton();
        panelOxu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttonOxu = new javax.swing.JButton();
        butonFaylOxu = new javax.swing.JButton();
        textFieldOxu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Gizlenecek melumat olan fayl:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Steqo konteyner:");

        buttonGizlet.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonGizlet.setText("Gizlet");
        buttonGizlet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGizletActionPerformed(evt);
            }
        });

        butonKonteyner.setText("Seç");
        butonKonteyner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonKonteynerActionPerformed(evt);
            }
        });

        textFieldMelumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMelumatActionPerformed(evt);
            }
        });

        butonGizli.setText("Seç");
        butonGizli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonGizliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGizletLayout = new javax.swing.GroupLayout(panelGizlet);
        panelGizlet.setLayout(panelGizletLayout);
        panelGizletLayout.setHorizontalGroup(
            panelGizletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGizletLayout.createSequentialGroup()
                .addGroup(panelGizletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGizletLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(butonGizli))
                    .addGroup(panelGizletLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(25, 25, 25)
                        .addComponent(butonKonteyner))
                    .addGroup(panelGizletLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelGizletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldKonteyner, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldMelumat, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelGizletLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(buttonGizlet)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGizletLayout.setVerticalGroup(
            panelGizletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGizletLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelGizletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butonKonteyner)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(textFieldKonteyner, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(panelGizletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(butonGizli))
                .addGap(18, 18, 18)
                .addComponent(textFieldMelumat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(buttonGizlet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Gizlet", panelGizlet);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Oxunacaq steqo fayl:");

        buttonOxu.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        buttonOxu.setText("OXU");
        buttonOxu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOxuActionPerformed(evt);
            }
        });

        butonFaylOxu.setText("Seç");
        butonFaylOxu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonFaylOxuActionPerformed(evt);
            }
        });

        textFieldOxu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldOxuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOxuLayout = new javax.swing.GroupLayout(panelOxu);
        panelOxu.setLayout(panelOxuLayout);
        panelOxuLayout.setHorizontalGroup(
            panelOxuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOxuLayout.createSequentialGroup()
                .addComponent(textFieldOxu, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(panelOxuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(butonFaylOxu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOxuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonOxu)
                .addGap(213, 213, 213))
        );
        panelOxuLayout.setVerticalGroup(
            panelOxuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOxuLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(panelOxuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(butonFaylOxu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldOxu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(buttonOxu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(105, 105, 105))
        );

        jTabbedPane1.addTab("Oxu", panelOxu);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("UGUR-STEGO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGizletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGizletActionPerformed

        byte[] bytesMelumat = null;
        byte[] bytesKonteyner = null;
        byte[] newPng = null;
        byte[] bytesSplit = "--".getBytes();

        Path pathKonteyner = Paths.get(textFieldKonteyner.getText());
        Path pathMelumat = Paths.get(textFieldMelumat.getText());
        String fileName = pathKonteyner.getFileName().toString().split("\\.")[0];
        String fileExtension = pathKonteyner.getFileName().toString().split("\\.")[1];

        try {
            bytesKonteyner = Files.readAllBytes(pathKonteyner);
            bytesMelumat = Files.readAllBytes(pathMelumat);
            newPng = new byte[bytesKonteyner.length + bytesMelumat.length + bytesSplit.length];

            for (int i = 0; i < newPng.length; i++) {
                if (i < bytesKonteyner.length) {
                    newPng[i] = bytesKonteyner[i];
                } else if (i < (bytesKonteyner.length + bytesSplit.length)) {
                    newPng[i] = bytesSplit[i - bytesKonteyner.length];
                } else if (i < newPng.length) {
                    newPng[i] = bytesMelumat[i - bytesKonteyner.length - bytesSplit.length];
                }
            }

            writeBytes(pathKonteyner.getParent() + "\\" + fileName + "-stego." + fileExtension, newPng);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonGizletActionPerformed



    private void buttonOxuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOxuActionPerformed
        Path pathOxu = Paths.get(textFieldOxu.getText());
        String fileName = pathOxu.getFileName().toString().split("\\.")[0];

        try {
            byte[] bytesOxu = Files.readAllBytes(pathOxu);
            String oxu = new String(bytesOxu, StandardCharsets.UTF_8);
            String[] sozlers = oxu.split("--");
            writeBytes(pathOxu.getParent().toString() + "\\" + fileName + "-decoded.txt", sozlers[sozlers.length - 1].getBytes());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_buttonOxuActionPerformed


    private void butonKonteynerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonKonteynerActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String fileName = file.getAbsolutePath();
        textFieldKonteyner.setText(fileName);
    }//GEN-LAST:event_butonKonteynerActionPerformed

    private void textFieldMelumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMelumatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMelumatActionPerformed

    private void textFieldOxuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldOxuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldOxuActionPerformed

    private void butonGizliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonGizliActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String fileName = file.getAbsolutePath();
        textFieldMelumat.setText(fileName);
    }//GEN-LAST:event_butonGizliActionPerformed

    private void butonFaylOxuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonFaylOxuActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String fileName = file.getAbsolutePath();
        textFieldOxu.setText(fileName);
    }//GEN-LAST:event_butonFaylOxuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butonFaylOxu;
    private javax.swing.JButton butonGizli;
    private javax.swing.JButton butonKonteyner;
    private javax.swing.JButton buttonGizlet;
    private javax.swing.JButton buttonOxu;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelGizlet;
    private javax.swing.JPanel panelOxu;
    private javax.swing.JTextField textFieldKonteyner;
    private javax.swing.JTextField textFieldMelumat;
    private javax.swing.JTextField textFieldOxu;
    // End of variables declaration//GEN-END:variables
}
